# fly.toml app configuration file generated for mgjules-go on 2024-12-13T16:06:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mgjules-go'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.22'

[env]
  PROD = true
  SERVER_PORT = 80
  STATIC = true

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
