version: "3.3"

services:
  gatus:
    image: twinproduction/gatus:latest
    restart: unless-stopped
    volumes:
      - ./gatus/config:/config
      - ./gatus/data:/data/
    ports:
      - "8003:8080"

  myspace:
    image: julesmike/myspace:v1
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8001:80"
    depends_on:
      - directus

  directus:
    image: directus/directus:9
    restart: unless-stopped
    env_file:
      - .env.directus
    ports:
      - "8002:80"
    volumes:
      - "./directus/uploads:/directus/uploads"
      - "./directus/database:/directus/database"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
